---
  - name: check waku-doc exists
    stat:
      path: /var/www/michael-doc
    register: doc_stat

  - name: copy docs files
    copy:
      src: ./files/michael-doc
      dest: /var/www
    when: not doc_stat.stat.exists

  - name: remove olds files
    file:
      path: /var/www/michael-doc/{{ item }}
      state: absent
    with_items:
      - yarn.lock
      - node_modules\

  - name: build to production
    command: chdir=/var/www/michael-doc {{ item }}
    with_items:
      - yarn install
      - yarn run build

  - name: check build production
    stat:
      path: /var/www/michael-doc/docs/.vuepress/dist
    register: build_stat

  - name: move dist in vuepress outside
    command: mv /var/www/michael-doc/docs/.vuepress/dist /var/www/michael-doc/
    when: build_stat.stat.exists

  - name: restart nginx
    service:
      name: nginx
      state: restarted
