---
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Template a file to /etc/files.conf
    template:
      src: ./templates/waku-docs.conf
      dest: /etc/nginx/conf.d/default.conf
      owner: app
      group: app
      mode: '0644'
