---
  - name: Install apache2-utils
    apt:
      name: apache2-utils
      state: present

  - name: Check exists password directory
    stat:
      path: /password/
    register: password_path_stats

  - name: Creates project directory
    file:
      path: /password
      state: directory
    when: not password_path_stats.stat.exists

  - name: Setup site password
    community.general.htpasswd:
      path: /password/.htpasswd
      name: username
      password: password
