---
  - name: Install postgresql
    apt: pkg={{ item }} state=latest
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev

  - name: Enable and Start postgresql
    service:
      name: postgresql
      state: started
      enabled: yes
